Rails.application.config.assets.precompile += %w( highcharts.js )
Rails.application.config.assets.precompile += %w( monitor.js )
Rails.application.config.assets.precompile += %w( list.js )
Rails.application.config.assets.precompile += %w( progressbar.gif )
Rails.application.config.assets.precompile += %w( loading.gif )